@php($editing = isset($ejercicio))
@php($equipamientosSeleccionados = old('equipamiento_ids', isset($ejercicio->equipamiento_ids) && $ejercicio->equipamiento_ids ? explode(',', $ejercicio->equipamiento_ids) : []))
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Nombre</label><input class="form-control" name="nombre" value="{{ old('nombre', $ejercicio->nombre ?? '') }}" required></div>
    @if($editing)<div class="col-md-6"><label class="form-label">Estado</label><select class="form-select" name="estado_ejercicio_id" required>@foreach($estados as $e)<option value="{{ $e->id }}" @selected(old('estado_ejercicio_id', $ejercicio->estado_ejercicio_id ?? null) == $e->id)>{{ $e->nombre }}</option>@endforeach</select></div>@else<div class="col-md-6"><label class="form-label">Estado</label><input class="form-control" value="Disponible" disabled></div>@endif
    <div class="col-md-6"><label class="form-label">Equipamientos <span class="text-muted">(opcional)</span></label><div class="input-group"><input id="equipamientosTexto" class="form-control" value="{{ $editing ? ($ejercicio->equipamiento ?? '') : '' }}" placeholder="Sin equipamientos seleccionados" readonly data-optional="true"><button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#modalEquipamientos">Elegir</button></div><div id="equipamientosInputs">@foreach($equipamientosSeleccionados as $id)<input type="hidden" name="equipamiento_ids[]" value="{{ $id }}">@endforeach</div></div>
    <div class="col-md-6"><label class="form-label">Grupo muscular</label><select class="form-select" name="grupo_muscular_id" required><option value="">Seleccione</option>@foreach($grupos as $grupo)<option value="{{ $grupo->id }}" @selected(old('grupo_muscular_id', $ejercicio->grupo_muscular_id ?? null) == $grupo->id)>{{ $grupo->nombre }}</option>@endforeach</select></div>
    <div class="col-12"><label class="form-label">Descripción <span class="text-muted">(opcional)</span></label><textarea class="form-control" name="descripcion" data-optional="true">{{ old('descripcion', $ejercicio->descripcion ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label">Instrucciones <span class="text-muted">(opcional)</span></label><textarea class="form-control" rows="5" name="instrucciones" data-optional="true">{{ old('instrucciones', $ejercicio->instrucciones ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label">Video <span class="text-muted">(opcional)</span></label><input type="url" class="form-control" name="video_url" data-optional="true" value="{{ old('video_url', $ejercicio->video_url ?? '') }}"></div>
</div>
<div class="modal fade" id="modalEquipamientos" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Elegir equipamientos</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="text-muted small">Marca todos los equipamientos que utiliza este ejercicio.</p><div class="vstack gap-2">@foreach($equipamientos as $item)<label class="border rounded p-2 d-flex gap-2 align-items-center"><input class="form-check-input equipo-check" type="checkbox" value="{{ $item->id }}" data-nombre="{{ $item->nombre }}" @checked(in_array((string) $item->id, array_map('strval', $equipamientosSeleccionados), true))><span>{{ $item->nombre }}</span></label>@endforeach</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button id="confirmarEquipamientos" type="button" class="btn btn-primary" data-bs-dismiss="modal">Confirmar selección</button></div></div></div></div>
@push('scripts')<script>document.getElementById('confirmarEquipamientos')?.addEventListener('click',()=>{const checks=[...document.querySelectorAll('.equipo-check:checked')],inputs=document.getElementById('equipamientosInputs');inputs.innerHTML=checks.map(x=>`<input type="hidden" name="equipamiento_ids[]" value="${x.value}">`).join('');document.getElementById('equipamientosTexto').value=checks.map(x=>x.dataset.nombre).join(', ')||'Sin equipamientos seleccionados'});</script>@endpush
