-- FitControl: procedimientos del módulo Asistencias.
DELIMITER $$
DROP PROCEDURE IF EXISTS sp_asistencias_filtrar$$
CREATE PROCEDURE sp_asistencias_filtrar(IN p_texto VARCHAR(150),IN p_cliente_id BIGINT UNSIGNED,IN p_metodo VARCHAR(30),IN p_solo_abiertas BOOLEAN,IN p_desde DATETIME,IN p_hasta DATETIME,IN p_limite INT UNSIGNED,IN p_offset INT UNSIGNED)
BEGIN IF p_limite IS NULL OR p_limite<1 OR p_limite>100 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El límite debe estar entre 1 y 100';END IF;SELECT a.id,a.cliente_id,c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,a.membresia_id,t.nombre tipo_membresia,a.entrada_at,a.salida_at,a.metodo_registro,a.observaciones,GREATEST(0,TIMESTAMPDIFF(MINUTE,a.entrada_at,COALESCE(a.salida_at,CURRENT_TIMESTAMP))) minutos,a.salida_at IS NULL abierta FROM asistencias a JOIN clientes c ON c.id=a.cliente_id JOIN membresias m ON m.id=a.membresia_id JOIN tipos_membresia t ON t.id=m.tipo_membresia_id WHERE (p_texto IS NULL OR p_texto='' OR c.numero_socio LIKE CONCAT('%',p_texto,'%') OR c.nombre LIKE CONCAT('%',p_texto,'%') OR c.apellido LIKE CONCAT('%',p_texto,'%')) AND (p_cliente_id IS NULL OR a.cliente_id=p_cliente_id) AND (p_metodo IS NULL OR p_metodo='' OR a.metodo_registro=p_metodo) AND (COALESCE(p_solo_abiertas,0)=0 OR a.salida_at IS NULL) AND (p_desde IS NULL OR a.entrada_at>=p_desde) AND (p_hasta IS NULL OR a.entrada_at<=p_hasta) ORDER BY a.entrada_at DESC,a.id DESC LIMIT p_limite OFFSET p_offset;END$$
DROP PROCEDURE IF EXISTS sp_asistencias_contar$$
CREATE PROCEDURE sp_asistencias_contar(IN p_texto VARCHAR(150),IN p_cliente_id BIGINT UNSIGNED,IN p_metodo VARCHAR(30),IN p_solo_abiertas BOOLEAN,IN p_desde DATETIME,IN p_hasta DATETIME) BEGIN SELECT COUNT(*) total FROM asistencias a JOIN clientes c ON c.id=a.cliente_id WHERE (p_texto IS NULL OR p_texto='' OR c.numero_socio LIKE CONCAT('%',p_texto,'%') OR c.nombre LIKE CONCAT('%',p_texto,'%') OR c.apellido LIKE CONCAT('%',p_texto,'%')) AND (p_cliente_id IS NULL OR a.cliente_id=p_cliente_id) AND (p_metodo IS NULL OR p_metodo='' OR a.metodo_registro=p_metodo) AND (COALESCE(p_solo_abiertas,0)=0 OR a.salida_at IS NULL) AND (p_desde IS NULL OR a.entrada_at>=p_desde) AND (p_hasta IS NULL OR a.entrada_at<=p_hasta);END$$
DROP PROCEDURE IF EXISTS sp_asistencias_obtener$$
CREATE PROCEDURE sp_asistencias_obtener(IN p_id BIGINT UNSIGNED) BEGIN IF NOT EXISTS(SELECT 1 FROM asistencias WHERE id=p_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La asistencia no existe';END IF;SELECT a.*,c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,t.nombre tipo_membresia,GREATEST(0,TIMESTAMPDIFF(MINUTE,a.entrada_at,COALESCE(a.salida_at,CURRENT_TIMESTAMP))) minutos FROM asistencias a JOIN clientes c ON c.id=a.cliente_id JOIN membresias m ON m.id=a.membresia_id JOIN tipos_membresia t ON t.id=m.tipo_membresia_id WHERE a.id=p_id;END$$
DROP PROCEDURE IF EXISTS sp_asistencias_validar_acceso$$
CREATE PROCEDURE sp_asistencias_validar_acceso(IN p_cliente_id BIGINT UNSIGNED,IN p_fecha DATETIME) BEGIN DECLARE v_fecha DATETIME DEFAULT COALESCE(p_fecha,CURRENT_TIMESTAMP);DECLARE v_membresia BIGINT UNSIGNED;DECLARE v_razon VARCHAR(255);IF EXISTS(SELECT 1 FROM asistencias WHERE cliente_id=p_cliente_id AND salida_at IS NULL) THEN SET v_razon='El cliente ya se encuentra dentro del gimnasio';ELSE SELECT m.id INTO v_membresia FROM membresias m JOIN estados_membresia e ON e.id=m.estado_membresia_id WHERE m.cliente_id=p_cliente_id AND m.deleted_at IS NULL AND m.bloqueo_activa=1 AND e.permite_acceso=1 AND DATE(v_fecha) BETWEEN m.fecha_inicio AND m.fecha_fin AND NOT EXISTS(SELECT 1 FROM suspensiones_membresia s WHERE s.membresia_id=m.id AND DATE(v_fecha)>=s.fecha_inicio AND (s.fecha_fin IS NULL OR DATE(v_fecha)<=s.fecha_fin)) LIMIT 1;IF v_membresia IS NULL THEN SET v_razon='No posee una membresía vigente con acceso permitido';END IF;END IF;SELECT v_razon IS NULL permitido,v_membresia membresia_id,COALESCE(v_razon,'Acceso permitido') mensaje,v_fecha fecha_validada;END$$
DROP PROCEDURE IF EXISTS sp_asistencias_registrar_entrada$$
CREATE PROCEDURE sp_asistencias_registrar_entrada(IN p_cliente_id BIGINT UNSIGNED,IN p_membresia_id BIGINT UNSIGNED,IN p_entrada DATETIME,IN p_metodo VARCHAR(30),IN p_usuario_id BIGINT UNSIGNED,IN p_observaciones TEXT)
BEGIN DECLARE v_entrada DATETIME DEFAULT COALESCE(p_entrada,CURRENT_TIMESTAMP);DECLARE EXIT HANDLER FOR 1062 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El cliente ya tiene una asistencia abierta';IF v_entrada>DATE_ADD(CURRENT_TIMESTAMP,INTERVAL 5 MINUTE) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La hora de entrada no puede estar en el futuro';END IF;IF NOT EXISTS(SELECT 1 FROM membresias m JOIN estados_membresia e ON e.id=m.estado_membresia_id WHERE m.id=p_membresia_id AND m.cliente_id=p_cliente_id AND m.deleted_at IS NULL AND m.bloqueo_activa=1 AND e.permite_acceso=1 AND DATE(v_entrada) BETWEEN m.fecha_inicio AND m.fecha_fin) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El cliente no posee una membresía válida para el acceso';END IF;IF EXISTS(SELECT 1 FROM suspensiones_membresia WHERE membresia_id=p_membresia_id AND DATE(v_entrada)>=fecha_inicio AND (fecha_fin IS NULL OR DATE(v_entrada)<=fecha_fin)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La membresía se encuentra congelada';END IF;INSERT INTO asistencias(cliente_id,membresia_id,entrada_at,bloqueo_abierta,metodo_registro,entrada_registrada_por,observaciones,created_at,updated_at) VALUES(p_cliente_id,p_membresia_id,v_entrada,1,COALESCE(p_metodo,'MANUAL'),p_usuario_id,p_observaciones,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);CALL sp_asistencias_obtener(LAST_INSERT_ID());END$$
DROP PROCEDURE IF EXISTS sp_asistencias_registrar_salida$$
CREATE PROCEDURE sp_asistencias_registrar_salida(IN p_asistencia_id BIGINT UNSIGNED,IN p_salida DATETIME,IN p_usuario_id BIGINT UNSIGNED) BEGIN DECLARE v_salida DATETIME DEFAULT COALESCE(p_salida,CURRENT_TIMESTAMP);DECLARE v_entrada DATETIME;DECLARE v_salida_existente DATETIME;SELECT entrada_at,salida_at INTO v_entrada,v_salida_existente FROM asistencias WHERE id=p_asistencia_id LIMIT 1;IF v_entrada IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La asistencia no existe';END IF;IF v_salida_existente IS NOT NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La asistencia ya fue cerrada';END IF;IF v_salida<=v_entrada THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La hora de salida debe ser posterior a la entrada';END IF;UPDATE asistencias SET salida_at=v_salida,bloqueo_abierta=NULL,salida_registrada_por=p_usuario_id,updated_at=CURRENT_TIMESTAMP WHERE id=p_asistencia_id;END$$

DROP PROCEDURE IF EXISTS sp_asistencias_reparar_fechas_futuras$$
CREATE PROCEDURE sp_asistencias_reparar_fechas_futuras()
BEGIN
 UPDATE asistencias SET entrada_at=created_at,updated_at=CURRENT_TIMESTAMP
 WHERE salida_at IS NULL AND entrada_at>DATE_ADD(created_at,INTERVAL 5 MINUTE);
 SELECT ROW_COUNT() corregidas;
END$$
DROP PROCEDURE IF EXISTS sp_asistencias_clientes_acceso$$
CREATE PROCEDURE sp_asistencias_clientes_acceso() BEGIN SELECT c.id,c.numero_socio,CONCAT(c.nombre,' ',c.apellido) nombre,m.id membresia_id,t.nombre membresia FROM clientes c JOIN membresias m ON m.cliente_id=c.id AND m.bloqueo_activa=1 AND m.deleted_at IS NULL JOIN estados_membresia e ON e.id=m.estado_membresia_id AND e.permite_acceso=1 JOIN tipos_membresia t ON t.id=m.tipo_membresia_id WHERE c.deleted_at IS NULL AND CURRENT_DATE BETWEEN m.fecha_inicio AND m.fecha_fin AND NOT EXISTS(SELECT 1 FROM asistencias a WHERE a.cliente_id=c.id AND a.salida_at IS NULL) AND NOT EXISTS(SELECT 1 FROM suspensiones_membresia s WHERE s.membresia_id=m.id AND CURRENT_DATE>=s.fecha_inicio AND (s.fecha_fin IS NULL OR CURRENT_DATE<=s.fecha_fin)) ORDER BY c.apellido,c.nombre LIMIT 500;END$$
DROP PROCEDURE IF EXISTS sp_asistencias_resumen$$
CREATE PROCEDURE sp_asistencias_resumen() BEGIN SELECT SUM(salida_at IS NULL) dentro_ahora,SUM(DATE(entrada_at)=CURRENT_DATE) entradas_hoy,COALESCE(ROUND(AVG(CASE WHEN salida_at IS NOT NULL AND DATE(entrada_at)=CURRENT_DATE THEN TIMESTAMPDIFF(MINUTE,entrada_at,salida_at) END)),0) promedio_minutos_hoy FROM asistencias;END$$
DELIMITER ;
