DELIMITER $$
DROP PROCEDURE IF EXISTS sp_ejercicios_filtrar$$
CREATE PROCEDURE sp_ejercicios_filtrar(IN p_texto VARCHAR(150),IN p_estado_id BIGINT UNSIGNED,IN p_grupo_id BIGINT UNSIGNED,IN p_equipamiento_id BIGINT UNSIGNED,IN p_limite INT UNSIGNED,IN p_offset INT UNSIGNED) BEGIN SELECT e.id,e.codigo,e.nombre,e.estado_ejercicio_id,ee.nombre estado,e.grupo_muscular_id,gm.nombre grupos_musculares,GROUP_CONCAT(eq.nombre ORDER BY eq.nombre SEPARATOR ', ') equipamiento,e.descripcion,e.video_url FROM ejercicios e JOIN estados_ejercicio ee ON ee.id=e.estado_ejercicio_id LEFT JOIN grupos_musculares gm ON gm.id=e.grupo_muscular_id LEFT JOIN ejercicio_equipamiento xe ON xe.ejercicio_id=e.id LEFT JOIN equipamientos eq ON eq.id=xe.equipamiento_id WHERE e.deleted_at IS NULL AND (p_texto IS NULL OR p_texto='' OR e.nombre LIKE CONCAT('%',p_texto,'%')) AND (p_estado_id IS NULL OR e.estado_ejercicio_id=p_estado_id) AND (p_grupo_id IS NULL OR e.grupo_muscular_id=p_grupo_id) AND (p_equipamiento_id IS NULL OR EXISTS(SELECT 1 FROM ejercicio_equipamiento y WHERE y.ejercicio_id=e.id AND y.equipamiento_id=p_equipamiento_id)) GROUP BY e.id,ee.nombre,gm.nombre ORDER BY e.nombre LIMIT p_limite OFFSET p_offset; END$$
DROP PROCEDURE IF EXISTS sp_ejercicios_contar$$
CREATE PROCEDURE sp_ejercicios_contar(IN p_texto VARCHAR(150),IN p_estado_id BIGINT UNSIGNED,IN p_grupo_id BIGINT UNSIGNED,IN p_equipamiento_id BIGINT UNSIGNED) BEGIN SELECT COUNT(*) total FROM ejercicios e WHERE e.deleted_at IS NULL AND (p_texto IS NULL OR p_texto='' OR e.nombre LIKE CONCAT('%',p_texto,'%')) AND (p_estado_id IS NULL OR e.estado_ejercicio_id=p_estado_id) AND (p_grupo_id IS NULL OR e.grupo_muscular_id=p_grupo_id) AND (p_equipamiento_id IS NULL OR EXISTS(SELECT 1 FROM ejercicio_equipamiento y WHERE y.ejercicio_id=e.id AND y.equipamiento_id=p_equipamiento_id)); END$$
DROP PROCEDURE IF EXISTS sp_ejercicios_obtener$$
CREATE PROCEDURE sp_ejercicios_obtener(IN p_id BIGINT UNSIGNED) BEGIN SELECT e.*,ee.nombre estado,gm.nombre grupo_muscular,GROUP_CONCAT(eq.nombre ORDER BY eq.nombre SEPARATOR ', ') equipamiento,GROUP_CONCAT(eq.id ORDER BY eq.id SEPARATOR ',') equipamiento_ids FROM ejercicios e JOIN estados_ejercicio ee ON ee.id=e.estado_ejercicio_id LEFT JOIN grupos_musculares gm ON gm.id=e.grupo_muscular_id LEFT JOIN ejercicio_equipamiento xe ON xe.ejercicio_id=e.id LEFT JOIN equipamientos eq ON eq.id=xe.equipamiento_id WHERE e.id=p_id AND e.deleted_at IS NULL GROUP BY e.id,ee.nombre,gm.nombre; END$$
DROP PROCEDURE IF EXISTS sp_ejercicios_crear$$
CREATE PROCEDURE sp_ejercicios_crear(IN p_codigo VARCHAR(40),IN p_nombre VARCHAR(120),IN p_grupo_id BIGINT UNSIGNED,IN p_descripcion TEXT,IN p_instrucciones TEXT,IN p_video VARCHAR(500)) BEGIN DECLARE v_id BIGINT UNSIGNED; DECLARE v_estado BIGINT UNSIGNED; SELECT id INTO v_estado FROM estados_ejercicio WHERE codigo='DISPONIBLE' LIMIT 1; INSERT INTO ejercicios(codigo,estado_ejercicio_id,grupo_muscular_id,nombre,descripcion,instrucciones,video_url,created_at,updated_at) VALUES(CONCAT('TMP-',UUID_SHORT()),v_estado,p_grupo_id,TRIM(p_nombre),NULLIF(TRIM(p_descripcion),''),NULLIF(TRIM(p_instrucciones),''),NULLIF(TRIM(p_video),''),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); SET v_id=LAST_INSERT_ID(); UPDATE ejercicios SET codigo=CONCAT('EJ-',LPAD(v_id,6,'0')) WHERE id=v_id; CALL sp_ejercicios_obtener(v_id); END$$
DROP PROCEDURE IF EXISTS sp_ejercicios_actualizar$$
CREATE PROCEDURE sp_ejercicios_actualizar(IN p_id BIGINT UNSIGNED,IN p_estado_id BIGINT UNSIGNED,IN p_nombre VARCHAR(120),IN p_grupo_id BIGINT UNSIGNED,IN p_descripcion TEXT,IN p_instrucciones TEXT,IN p_video VARCHAR(500)) BEGIN UPDATE ejercicios SET estado_ejercicio_id=p_estado_id,nombre=TRIM(p_nombre),grupo_muscular_id=p_grupo_id,descripcion=NULLIF(TRIM(p_descripcion),''),instrucciones=NULLIF(TRIM(p_instrucciones),''),video_url=NULLIF(TRIM(p_video),''),updated_at=CURRENT_TIMESTAMP WHERE id=p_id AND deleted_at IS NULL; END$$
DROP PROCEDURE IF EXISTS sp_ejercicios_cambiar_estado$$
CREATE PROCEDURE sp_ejercicios_cambiar_estado(IN p_id BIGINT UNSIGNED,IN p_estado_id BIGINT UNSIGNED) BEGIN UPDATE ejercicios SET estado_ejercicio_id=p_estado_id WHERE id=p_id; END$$
DROP PROCEDURE IF EXISTS sp_ejercicios_eliminar$$
CREATE PROCEDURE sp_ejercicios_eliminar(IN p_id BIGINT UNSIGNED) BEGIN UPDATE ejercicios SET deleted_at=CURRENT_TIMESTAMP WHERE id=p_id; END$$
DELIMITER ;
