-- FitControl: procedimientos del módulo Evaluaciones Físicas.
DELIMITER $$
DROP PROCEDURE IF EXISTS sp_evaluaciones_filtrar$$
CREATE PROCEDURE sp_evaluaciones_filtrar(IN p_texto VARCHAR(150),IN p_cliente_id BIGINT UNSIGNED,IN p_evaluador_id BIGINT UNSIGNED,IN p_desde DATE,IN p_hasta DATE,IN p_limite INT UNSIGNED,IN p_offset INT UNSIGNED) BEGIN SELECT e.id,e.cliente_id,c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,e.evaluador_id,CONCAT(p.nombre,' ',p.apellido) evaluador,e.evaluada_at,e.metodo,e.observaciones,(SELECT COUNT(*) FROM detalles_evaluacion d WHERE d.evaluacion_fisica_id=e.id) medidas FROM evaluaciones_fisicas e JOIN clientes c ON c.id=e.cliente_id JOIN personal p ON p.id=e.evaluador_id WHERE e.deleted_at IS NULL AND (p_texto IS NULL OR p_texto='' OR c.numero_socio LIKE CONCAT('%',p_texto,'%') OR c.nombre LIKE CONCAT('%',p_texto,'%') OR c.apellido LIKE CONCAT('%',p_texto,'%') OR e.metodo LIKE CONCAT('%',p_texto,'%')) AND (p_cliente_id IS NULL OR e.cliente_id=p_cliente_id) AND (p_evaluador_id IS NULL OR e.evaluador_id=p_evaluador_id) AND (p_desde IS NULL OR DATE(e.evaluada_at)>=p_desde) AND (p_hasta IS NULL OR DATE(e.evaluada_at)<=p_hasta) ORDER BY e.evaluada_at DESC,e.id DESC LIMIT p_limite OFFSET p_offset; END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_contar$$
CREATE PROCEDURE sp_evaluaciones_contar(IN p_texto VARCHAR(150),IN p_cliente_id BIGINT UNSIGNED,IN p_evaluador_id BIGINT UNSIGNED,IN p_desde DATE,IN p_hasta DATE) BEGIN SELECT COUNT(*) total FROM evaluaciones_fisicas e JOIN clientes c ON c.id=e.cliente_id WHERE e.deleted_at IS NULL AND (p_texto IS NULL OR p_texto='' OR c.numero_socio LIKE CONCAT('%',p_texto,'%') OR c.nombre LIKE CONCAT('%',p_texto,'%') OR c.apellido LIKE CONCAT('%',p_texto,'%') OR e.metodo LIKE CONCAT('%',p_texto,'%')) AND (p_cliente_id IS NULL OR e.cliente_id=p_cliente_id) AND (p_evaluador_id IS NULL OR e.evaluador_id=p_evaluador_id) AND (p_desde IS NULL OR DATE(e.evaluada_at)>=p_desde) AND (p_hasta IS NULL OR DATE(e.evaluada_at)<=p_hasta); END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_fisicas_obtener$$
CREATE PROCEDURE sp_evaluaciones_fisicas_obtener(IN p_id BIGINT UNSIGNED) BEGIN IF NOT EXISTS(SELECT 1 FROM evaluaciones_fisicas WHERE id=p_id AND deleted_at IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La evaluación no existe';END IF;SELECT e.*,c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,CONCAT(p.nombre,' ',p.apellido) evaluador FROM evaluaciones_fisicas e JOIN clientes c ON c.id=e.cliente_id JOIN personal p ON p.id=e.evaluador_id WHERE e.id=p_id;END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_medidas$$
CREATE PROCEDURE sp_evaluaciones_medidas(IN p_id BIGINT UNSIGNED) BEGIN SELECT d.id,d.tipo_medida_id,t.codigo,t.nombre,d.valor,d.unidad_snapshot,t.decimales,d.instrumento,d.observaciones,d.created_at FROM detalles_evaluacion d JOIN tipos_medida t ON t.id=d.tipo_medida_id WHERE d.evaluacion_fisica_id=p_id ORDER BY t.nombre; END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_historial_cliente$$
CREATE PROCEDURE sp_evaluaciones_historial_cliente(IN p_cliente_id BIGINT UNSIGNED) BEGIN SELECT e.id,e.evaluada_at,e.metodo,CONCAT(p.nombre,' ',p.apellido) evaluador,COUNT(d.id) medidas FROM evaluaciones_fisicas e JOIN personal p ON p.id=e.evaluador_id LEFT JOIN detalles_evaluacion d ON d.evaluacion_fisica_id=e.id WHERE e.cliente_id=p_cliente_id AND e.deleted_at IS NULL GROUP BY e.id,p.nombre,p.apellido ORDER BY e.evaluada_at DESC; END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_comparar$$
CREATE PROCEDURE sp_evaluaciones_comparar(IN p_evaluacion_base BIGINT UNSIGNED,IN p_evaluacion_comparada BIGINT UNSIGNED) BEGIN DECLARE v_cliente1 BIGINT UNSIGNED;DECLARE v_cliente2 BIGINT UNSIGNED;SELECT cliente_id INTO v_cliente1 FROM evaluaciones_fisicas WHERE id=p_evaluacion_base AND deleted_at IS NULL;SELECT cliente_id INTO v_cliente2 FROM evaluaciones_fisicas WHERE id=p_evaluacion_comparada AND deleted_at IS NULL;IF v_cliente1 IS NULL OR v_cliente1<>v_cliente2 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Las evaluaciones deben existir y pertenecer al mismo cliente';END IF;SELECT t.id tipo_medida_id,t.nombre,d1.valor valor_base,d2.valor valor_comparado,d2.valor-d1.valor diferencia,CASE WHEN d1.valor=0 THEN NULL ELSE ROUND(((d2.valor-d1.valor)/ABS(d1.valor))*100,2) END variacion_porcentual,d1.unidad_snapshot unidad FROM detalles_evaluacion d1 JOIN detalles_evaluacion d2 ON d2.tipo_medida_id=d1.tipo_medida_id AND d2.evaluacion_fisica_id=p_evaluacion_comparada JOIN tipos_medida t ON t.id=d1.tipo_medida_id WHERE d1.evaluacion_fisica_id=p_evaluacion_base ORDER BY t.nombre; END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_agregar_medida$$
CREATE PROCEDURE sp_evaluaciones_agregar_medida(IN p_evaluacion_id BIGINT UNSIGNED,IN p_tipo_id BIGINT UNSIGNED,IN p_valor DECIMAL(12,4),IN p_instrumento VARCHAR(100),IN p_observaciones TEXT) BEGIN DECLARE v_unidad VARCHAR(20);DECLARE v_min DECIMAL(12,4);DECLARE v_max DECIMAL(12,4);IF NOT EXISTS(SELECT 1 FROM evaluaciones_fisicas WHERE id=p_evaluacion_id AND deleted_at IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La evaluación no existe';END IF;SELECT unidad,valor_minimo,valor_maximo INTO v_unidad,v_min,v_max FROM tipos_medida WHERE id=p_tipo_id AND activo=1;IF v_unidad IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El tipo de medida no está disponible';END IF;IF (v_min IS NOT NULL AND p_valor<v_min) OR (v_max IS NOT NULL AND p_valor>v_max) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El valor está fuera del rango permitido';END IF;INSERT INTO detalles_evaluacion(evaluacion_fisica_id,tipo_medida_id,valor,unidad_snapshot,instrumento,observaciones,created_at,updated_at) VALUES(p_evaluacion_id,p_tipo_id,p_valor,v_unidad,p_instrumento,p_observaciones,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE valor=VALUES(valor),unidad_snapshot=VALUES(unidad_snapshot),instrumento=VALUES(instrumento),observaciones=VALUES(observaciones),updated_at=CURRENT_TIMESTAMP;END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_clientes$$
CREATE PROCEDURE sp_evaluaciones_clientes() BEGIN SELECT id,numero_socio,CONCAT(nombre,' ',apellido) nombre FROM clientes WHERE deleted_at IS NULL ORDER BY apellido,nombre LIMIT 500;END$$
DROP PROCEDURE IF EXISTS sp_evaluaciones_evaluadores$$
CREATE PROCEDURE sp_evaluaciones_evaluadores() BEGIN SELECT id,codigo_empleado,CONCAT(nombre,' ',apellido) nombre FROM personal WHERE deleted_at IS NULL ORDER BY apellido,nombre LIMIT 500;END$$
DELIMITER ;
