-- FitControl: motor de reportes operativos.
DELIMITER $$
DROP PROCEDURE IF EXISTS sp_reportes_generar$$
CREATE PROCEDURE sp_reportes_generar(IN p_reporte VARCHAR(30),IN p_desde DATE,IN p_hasta DATE,IN p_busqueda VARCHAR(150),IN p_estado_id BIGINT UNSIGNED)
BEGIN
 IF p_reporte='clientes' THEN
  SELECT c.numero_socio,c.nombre,c.apellido,e.nombre estado,c.telefono,c.correo_electronico,c.fecha_registro FROM clientes c JOIN estados_cliente e ON e.id=c.estado_cliente_id WHERE c.deleted_at IS NULL AND (p_busqueda IS NULL OR p_busqueda='' OR c.numero_socio LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_estado_id IS NULL OR c.estado_cliente_id=p_estado_id) AND (p_desde IS NULL OR c.fecha_registro>=p_desde) AND (p_hasta IS NULL OR c.fecha_registro<=p_hasta) ORDER BY c.apellido,c.nombre LIMIT 10000;
 ELSEIF p_reporte='personal' THEN
  SELECT p.codigo_empleado,p.nombre,p.apellido,c.nombre cargo,e.nombre estado,p.telefono,p.correo_electronico,p.fecha_contratacion FROM personal p JOIN cargos c ON c.id=p.cargo_id JOIN estados_personal e ON e.id=p.estado_personal_id WHERE p.deleted_at IS NULL AND (p_busqueda IS NULL OR p_busqueda='' OR p.codigo_empleado LIKE CONCAT('%',p_busqueda,'%') OR p.nombre LIKE CONCAT('%',p_busqueda,'%') OR p.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_estado_id IS NULL OR p.estado_personal_id=p_estado_id) AND (p_desde IS NULL OR p.fecha_contratacion>=p_desde) AND (p_hasta IS NULL OR p.fecha_contratacion<=p_hasta) ORDER BY p.apellido,p.nombre LIMIT 10000;
 ELSEIF p_reporte='pagos' THEN
  SELECT p.numero_recibo,CONCAT(c.nombre,' ',c.apellido) cliente,m.nombre metodo,e.nombre estado,p.monto,p.moneda,p.referencia,p.pagado_at FROM pagos p JOIN clientes c ON c.id=p.cliente_id JOIN metodos_pago m ON m.id=p.metodo_pago_id JOIN estados_pago e ON e.id=p.estado_pago_id WHERE (p_busqueda IS NULL OR p_busqueda='' OR p.numero_recibo LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_estado_id IS NULL OR p.estado_pago_id=p_estado_id) AND (p_desde IS NULL OR p.pagado_at>=p_desde) AND (p_hasta IS NULL OR p.pagado_at<p_hasta+INTERVAL 1 DAY) ORDER BY p.pagado_at DESC LIMIT 10000;
 ELSEIF p_reporte='cobros' THEN
  SELECT cc.numero_cargo,CONCAT(c.nombre,' ',c.apellido) cliente,e.nombre estado,cc.concepto,cc.total,COALESCE(SUM(a.monto_aplicado),0) pagado,cc.total-COALESCE(SUM(a.monto_aplicado),0) saldo,cc.moneda,cc.fecha_emision,cc.fecha_vencimiento FROM cargos_cobro cc JOIN clientes c ON c.id=cc.cliente_id JOIN estados_cargo_cobro e ON e.id=cc.estado_cargo_cobro_id LEFT JOIN aplicaciones_pago a ON a.cargo_cobro_id=cc.id WHERE cc.deleted_at IS NULL AND (p_busqueda IS NULL OR p_busqueda='' OR cc.numero_cargo LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_estado_id IS NULL OR cc.estado_cargo_cobro_id=p_estado_id) AND (p_desde IS NULL OR cc.fecha_emision>=p_desde) AND (p_hasta IS NULL OR cc.fecha_emision<=p_hasta) GROUP BY cc.id,c.nombre,c.apellido,e.nombre ORDER BY cc.fecha_emision DESC LIMIT 10000;
 ELSEIF p_reporte='asistencias' THEN
  SELECT c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,a.entrada_at,a.salida_at,TIMESTAMPDIFF(MINUTE,a.entrada_at,COALESCE(a.salida_at,CURRENT_TIMESTAMP)) duracion_minutos,a.metodo_registro FROM asistencias a JOIN clientes c ON c.id=a.cliente_id WHERE (p_busqueda IS NULL OR p_busqueda='' OR c.numero_socio LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_desde IS NULL OR a.entrada_at>=p_desde) AND (p_hasta IS NULL OR a.entrada_at<p_hasta+INTERVAL 1 DAY) ORDER BY a.entrada_at DESC LIMIT 10000;
 ELSEIF p_reporte='membresias' THEN
  SELECT c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,t.nombre tipo,e.nombre estado,m.fecha_inicio,m.fecha_fin,m.precio_contratado,m.moneda,m.origen FROM membresias m JOIN clientes c ON c.id=m.cliente_id JOIN tipos_membresia t ON t.id=m.tipo_membresia_id JOIN estados_membresia e ON e.id=m.estado_membresia_id WHERE m.deleted_at IS NULL AND (p_busqueda IS NULL OR p_busqueda='' OR c.numero_socio LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_estado_id IS NULL OR m.estado_membresia_id=p_estado_id) AND (p_desde IS NULL OR m.fecha_fin>=p_desde) AND (p_hasta IS NULL OR m.fecha_inicio<=p_hasta) ORDER BY m.fecha_inicio DESC LIMIT 10000;
 ELSEIF p_reporte='evaluaciones' THEN
  SELECT c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,CONCAT(p.nombre,' ',p.apellido) evaluador,e.evaluada_at,e.metodo,COUNT(d.id) medidas,e.observaciones FROM evaluaciones_fisicas e JOIN clientes c ON c.id=e.cliente_id JOIN personal p ON p.id=e.evaluador_id LEFT JOIN detalles_evaluacion d ON d.evaluacion_fisica_id=e.id WHERE e.deleted_at IS NULL AND (p_busqueda IS NULL OR p_busqueda='' OR c.numero_socio LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_desde IS NULL OR e.evaluada_at>=p_desde) AND (p_hasta IS NULL OR e.evaluada_at<p_hasta+INTERVAL 1 DAY) GROUP BY e.id,c.numero_socio,c.nombre,c.apellido,p.nombre,p.apellido ORDER BY e.evaluada_at DESC LIMIT 10000;
 ELSEIF p_reporte='entrenamientos' THEN
  SELECT c.numero_socio,CONCAT(c.nombre,' ',c.apellido) cliente,r.nombre rutina,s.nombre sesion,e.iniciado_at,e.finalizado_at,TIMESTAMPDIFF(MINUTE,e.iniciado_at,COALESCE(e.finalizado_at,CURRENT_TIMESTAMP)) duracion_minutos,e.notas observaciones FROM entrenamientos_realizados e JOIN clientes c ON c.id=e.cliente_id LEFT JOIN versiones_rutina v ON v.id=e.version_rutina_id LEFT JOIN rutinas r ON r.id=v.rutina_id LEFT JOIN sesiones_rutina s ON s.id=e.sesion_rutina_id WHERE (p_busqueda IS NULL OR p_busqueda='' OR c.numero_socio LIKE CONCAT('%',p_busqueda,'%') OR c.nombre LIKE CONCAT('%',p_busqueda,'%') OR c.apellido LIKE CONCAT('%',p_busqueda,'%')) AND (p_desde IS NULL OR e.iniciado_at>=p_desde) AND (p_hasta IS NULL OR e.iniciado_at<p_hasta+INTERVAL 1 DAY) ORDER BY e.iniciado_at DESC LIMIT 10000;
 ELSE SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tipo de reporte no permitido';
 END IF;
END$$
DELIMITER ;
