-- FitControl: procedimientos del módulo Rutinas.
DELIMITER $$
DROP PROCEDURE IF EXISTS sp_rutinas_filtrar$$
CREATE PROCEDURE sp_rutinas_filtrar(IN p_texto VARCHAR(150),IN p_cliente_id BIGINT UNSIGNED,IN p_entrenador_id BIGINT UNSIGNED,IN p_estado_id BIGINT UNSIGNED,IN p_limite INT UNSIGNED,IN p_offset INT UNSIGNED)
BEGIN SELECT r.id,r.nombre,r.descripcion,r.cliente_id,CONCAT(c.nombre,' ',c.apellido) cliente,r.entrenador_id,CONCAT(p.nombre,' ',p.apellido) entrenador,r.estado_rutina_id,e.nombre estado,r.fecha_inicio,r.fecha_fin,r.version_activa_id,v.numero_version version_activa,(SELECT COUNT(*) FROM versiones_rutina x WHERE x.rutina_id=r.id) versiones FROM rutinas r JOIN clientes c ON c.id=r.cliente_id JOIN personal p ON p.id=r.entrenador_id JOIN estados_rutina e ON e.id=r.estado_rutina_id LEFT JOIN versiones_rutina v ON v.id=r.version_activa_id WHERE r.deleted_at IS NULL AND (p_texto IS NULL OR p_texto='' OR r.nombre LIKE CONCAT('%',p_texto,'%') OR c.nombre LIKE CONCAT('%',p_texto,'%') OR c.apellido LIKE CONCAT('%',p_texto,'%')) AND (p_cliente_id IS NULL OR r.cliente_id=p_cliente_id) AND (p_entrenador_id IS NULL OR r.entrenador_id=p_entrenador_id) AND (p_estado_id IS NULL OR r.estado_rutina_id=p_estado_id) ORDER BY r.created_at DESC LIMIT p_limite OFFSET p_offset; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_contar$$
CREATE PROCEDURE sp_rutinas_contar(IN p_texto VARCHAR(150),IN p_cliente_id BIGINT UNSIGNED,IN p_entrenador_id BIGINT UNSIGNED,IN p_estado_id BIGINT UNSIGNED) BEGIN SELECT COUNT(*) total FROM rutinas r JOIN clientes c ON c.id=r.cliente_id WHERE r.deleted_at IS NULL AND (p_texto IS NULL OR p_texto='' OR r.nombre LIKE CONCAT('%',p_texto,'%') OR c.nombre LIKE CONCAT('%',p_texto,'%') OR c.apellido LIKE CONCAT('%',p_texto,'%')) AND (p_cliente_id IS NULL OR r.cliente_id=p_cliente_id) AND (p_entrenador_id IS NULL OR r.entrenador_id=p_entrenador_id) AND (p_estado_id IS NULL OR r.estado_rutina_id=p_estado_id); END$$
DROP PROCEDURE IF EXISTS sp_rutinas_obtener$$
CREATE PROCEDURE sp_rutinas_obtener(IN p_id BIGINT UNSIGNED) BEGIN IF NOT EXISTS(SELECT 1 FROM rutinas WHERE id=p_id AND deleted_at IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La rutina no existe'; END IF; SELECT r.*,CONCAT(c.nombre,' ',c.apellido) cliente,c.numero_socio,CONCAT(p.nombre,' ',p.apellido) entrenador,e.nombre estado,v.numero_version version_activa FROM rutinas r JOIN clientes c ON c.id=r.cliente_id JOIN personal p ON p.id=r.entrenador_id JOIN estados_rutina e ON e.id=r.estado_rutina_id LEFT JOIN versiones_rutina v ON v.id=r.version_activa_id WHERE r.id=p_id; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_versiones$$
CREATE PROCEDURE sp_rutinas_versiones(IN p_id BIGINT UNSIGNED) BEGIN SELECT v.*,(r.version_activa_id=v.id) es_activa,(SELECT COUNT(*) FROM sesiones_rutina s WHERE s.version_rutina_id=v.id) sesiones FROM versiones_rutina v JOIN rutinas r ON r.id=v.rutina_id WHERE v.rutina_id=p_id ORDER BY v.numero_version DESC; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_contenido_version$$
CREATE PROCEDURE sp_rutinas_contenido_version(IN p_version_id BIGINT UNSIGNED) BEGIN SELECT s.id sesion_id,s.numero_sesion,s.nombre sesion,s.dia_semana,s.indicaciones indicaciones_sesion,er.id detalle_id,er.orden,ej.id ejercicio_id,ej.nombre ejercicio,er.series,er.repeticiones_min,er.repeticiones_max,er.duracion_segundos,er.distancia,er.peso,er.descanso_segundos,er.rpe,er.rir,er.tempo,er.indicaciones FROM sesiones_rutina s LEFT JOIN ejercicios_rutina er ON er.sesion_rutina_id=s.id LEFT JOIN ejercicios ej ON ej.id=er.ejercicio_id WHERE s.version_rutina_id=p_version_id ORDER BY s.numero_sesion,er.orden; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_historial$$
CREATE PROCEDURE sp_rutinas_historial(IN p_id BIGINT UNSIGNED) BEGIN SELECT h.id,va.numero_version version_anterior,vn.numero_version version_nueva,h.motivo,h.activada_por,h.activada_at FROM historial_versiones_rutina h LEFT JOIN versiones_rutina va ON va.id=h.version_anterior_id JOIN versiones_rutina vn ON vn.id=h.version_nueva_id WHERE h.rutina_id=p_id ORDER BY h.activada_at DESC; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_activar_version$$
CREATE PROCEDURE sp_rutinas_activar_version(IN p_rutina_id BIGINT UNSIGNED,IN p_version_id BIGINT UNSIGNED,IN p_motivo VARCHAR(255),IN p_usuario_id BIGINT UNSIGNED)
BEGIN DECLARE v_anterior BIGINT UNSIGNED; DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END; IF NOT EXISTS(SELECT 1 FROM versiones_rutina WHERE id=p_version_id AND rutina_id=p_rutina_id AND publicada_at IS NOT NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La versión no pertenece a la rutina o no está publicada'; END IF; START TRANSACTION; SELECT version_activa_id INTO v_anterior FROM rutinas WHERE id=p_rutina_id AND deleted_at IS NULL FOR UPDATE; IF v_anterior=p_version_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La versión ya está activa'; END IF; UPDATE rutinas SET version_activa_id=p_version_id,updated_at=CURRENT_TIMESTAMP WHERE id=p_rutina_id; INSERT INTO historial_versiones_rutina(rutina_id,version_anterior_id,version_nueva_id,motivo,activada_por,activada_at,created_at,updated_at) VALUES(p_rutina_id,v_anterior,p_version_id,p_motivo,p_usuario_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); COMMIT; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_duplicar$$
CREATE PROCEDURE sp_rutinas_duplicar(IN p_origen_id BIGINT UNSIGNED,IN p_cliente_id BIGINT UNSIGNED,IN p_entrenador_id BIGINT UNSIGNED,IN p_nombre VARCHAR(120),IN p_usuario_id BIGINT UNSIGNED)
BEGIN DECLARE v_nueva BIGINT UNSIGNED;DECLARE v_version_origen BIGINT UNSIGNED;DECLARE v_version_nueva BIGINT UNSIGNED;DECLARE done INT DEFAULT 0;DECLARE v_sesion BIGINT UNSIGNED;DECLARE v_sesion_nueva BIGINT UNSIGNED;DECLARE cur CURSOR FOR SELECT id FROM sesiones_rutina WHERE version_rutina_id=v_version_origen ORDER BY numero_sesion;DECLARE CONTINUE HANDLER FOR NOT FOUND SET done=1;DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK;RESIGNAL;END;
 SELECT COALESCE(version_activa_id,(SELECT id FROM versiones_rutina WHERE rutina_id=p_origen_id ORDER BY numero_version DESC LIMIT 1)) INTO v_version_origen FROM rutinas WHERE id=p_origen_id AND deleted_at IS NULL; IF v_version_origen IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La rutina origen no tiene versiones'; END IF; START TRANSACTION; INSERT INTO rutinas(cliente_id,entrenador_id,estado_rutina_id,nombre,descripcion,fecha_inicio,fecha_fin,creada_por,created_at,updated_at) SELECT p_cliente_id,p_entrenador_id,estado_rutina_id,p_nombre,descripcion,CURRENT_DATE,NULL,p_usuario_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM rutinas WHERE id=p_origen_id; SET v_nueva=LAST_INSERT_ID(); INSERT INTO versiones_rutina(rutina_id,numero_version,notas_cambio,creada_por,created_at,updated_at) VALUES(v_nueva,1,CONCAT('Duplicada de rutina #',p_origen_id),p_usuario_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);SET v_version_nueva=LAST_INSERT_ID(); OPEN cur;read_loop: LOOP FETCH cur INTO v_sesion;IF done=1 THEN LEAVE read_loop;END IF;INSERT INTO sesiones_rutina(version_rutina_id,numero_sesion,nombre,dia_semana,indicaciones,created_at,updated_at) SELECT v_version_nueva,numero_sesion,nombre,dia_semana,indicaciones,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM sesiones_rutina WHERE id=v_sesion;SET v_sesion_nueva=LAST_INSERT_ID();INSERT INTO ejercicios_rutina(sesion_rutina_id,ejercicio_id,orden,series,repeticiones_min,repeticiones_max,duracion_segundos,distancia,peso,descanso_segundos,rpe,rir,tempo,indicaciones,created_at,updated_at) SELECT v_sesion_nueva,ejercicio_id,orden,series,repeticiones_min,repeticiones_max,duracion_segundos,distancia,peso,descanso_segundos,rpe,rir,tempo,indicaciones,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM ejercicios_rutina WHERE sesion_rutina_id=v_sesion;END LOOP;CLOSE cur;COMMIT;CALL sp_rutinas_obtener(v_nueva); END$$
DROP PROCEDURE IF EXISTS sp_rutinas_eliminar_sesion$$
CREATE PROCEDURE sp_rutinas_eliminar_sesion(IN p_id BIGINT UNSIGNED) BEGIN IF EXISTS(SELECT 1 FROM versiones_rutina v JOIN sesiones_rutina s ON s.version_rutina_id=v.id WHERE s.id=p_id AND v.publicada_at IS NOT NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='No puede modificar una versión publicada'; END IF; DELETE FROM ejercicios_rutina WHERE sesion_rutina_id=p_id;DELETE FROM sesiones_rutina WHERE id=p_id;IF ROW_COUNT()=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La sesión no existe';END IF; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_eliminar_ejercicio$$
CREATE PROCEDURE sp_rutinas_eliminar_ejercicio(IN p_id BIGINT UNSIGNED) BEGIN IF EXISTS(SELECT 1 FROM versiones_rutina v JOIN sesiones_rutina s ON s.version_rutina_id=v.id JOIN ejercicios_rutina e ON e.sesion_rutina_id=s.id WHERE e.id=p_id AND v.publicada_at IS NOT NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='No puede modificar una versión publicada'; END IF;DELETE FROM ejercicios_rutina WHERE id=p_id;IF ROW_COUNT()=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El ejercicio no existe en la sesión';END IF; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_agregar_sesion$$
CREATE PROCEDURE sp_rutinas_agregar_sesion(IN p_version_id BIGINT UNSIGNED,IN p_numero SMALLINT UNSIGNED,IN p_nombre VARCHAR(100),IN p_dia TINYINT UNSIGNED,IN p_indicaciones TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM versiones_rutina WHERE id=p_version_id AND publicada_at IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La versión no existe o ya fue publicada';END IF;INSERT INTO sesiones_rutina(version_rutina_id,numero_sesion,nombre,dia_semana,indicaciones,created_at,updated_at) VALUES(p_version_id,p_numero,TRIM(p_nombre),p_dia,p_indicaciones,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);END$$
DROP PROCEDURE IF EXISTS sp_rutinas_agregar_ejercicio$$
CREATE PROCEDURE sp_rutinas_agregar_ejercicio(IN p_sesion_id BIGINT UNSIGNED,IN p_ejercicio_id BIGINT UNSIGNED,IN p_orden SMALLINT UNSIGNED,IN p_series SMALLINT UNSIGNED,IN p_rep_min SMALLINT UNSIGNED,IN p_rep_max SMALLINT UNSIGNED,IN p_duracion INT UNSIGNED,IN p_distancia DECIMAL(10,2),IN p_peso DECIMAL(8,2),IN p_descanso SMALLINT UNSIGNED,IN p_rpe DECIMAL(3,1),IN p_rir TINYINT UNSIGNED,IN p_tempo VARCHAR(20),IN p_indicaciones TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM sesiones_rutina s JOIN versiones_rutina v ON v.id=s.version_rutina_id WHERE s.id=p_sesion_id AND v.publicada_at IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La sesión no existe o su versión ya fue publicada';END IF;INSERT INTO ejercicios_rutina(sesion_rutina_id,ejercicio_id,orden,series,repeticiones_min,repeticiones_max,duracion_segundos,distancia,peso,descanso_segundos,rpe,rir,tempo,indicaciones,created_at,updated_at) VALUES(p_sesion_id,p_ejercicio_id,p_orden,p_series,p_rep_min,p_rep_max,p_duracion,p_distancia,p_peso,p_descanso,p_rpe,p_rir,p_tempo,p_indicaciones,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);END$$
DROP PROCEDURE IF EXISTS sp_rutinas_clientes$$
CREATE PROCEDURE sp_rutinas_clientes() BEGIN SELECT id,numero_socio,CONCAT(nombre,' ',apellido) nombre FROM clientes WHERE deleted_at IS NULL ORDER BY apellido,nombre LIMIT 500; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_entrenadores$$
CREATE PROCEDURE sp_rutinas_entrenadores() BEGIN SELECT id,codigo_empleado,CONCAT(nombre,' ',apellido) nombre FROM personal WHERE deleted_at IS NULL ORDER BY apellido,nombre LIMIT 500; END$$
DROP PROCEDURE IF EXISTS sp_rutinas_ejercicios$$
CREATE PROCEDURE sp_rutinas_ejercicios() BEGIN SELECT e.id,e.codigo,e.nombre FROM ejercicios e JOIN estados_ejercicio s ON s.id=e.estado_ejercicio_id WHERE e.deleted_at IS NULL ORDER BY e.nombre LIMIT 1000; END$$
DELIMITER ;
