@extends('layouts.app')
@section('title','Membresía')
@php($permissions=session('permissions',[])) @php($can=static fn(string $p):bool=>in_array('*',$permissions,true)||in_array($p,$permissions,true))
@section('content')
<x-page-header :title="$membresia->cliente" :subtitle="$membresia->tipo.' · '.$membresia->estado">@if($contrato)<x-button :href="route('membresias.contrato',$membresia->id)" variant="outline-primary" icon="bi-file-earmark-pdf">Contrato</x-button>@endif</x-page-header>
<div class="row g-4 mb-4"><div class="col-lg-8"><x-card title="Resumen"><div class="row g-3"><div class="col-md-3"><small class="text-muted d-block">Socio</small>{{ $membresia->numero_socio }}</div><div class="col-md-3"><small class="text-muted d-block">Estado</small><span class="badge text-bg-primary">{{ $membresia->estado }}</span></div><div class="col-md-3"><small class="text-muted d-block">Precio</small>{{ number_format($membresia->precio_contratado,2) }} {{ $membresia->moneda }}</div><div class="col-md-3"><small class="text-muted d-block">Vigencia</small>{{ \Illuminate\Support\Carbon::parse($membresia->fecha_inicio)->format('d/m/Y') }} – {{ \Illuminate\Support\Carbon::parse($membresia->fecha_fin)->format('d/m/Y') }}</div></div></x-card></div><div class="col-lg-4"><x-card title="Siguiente acción">@if($membresia->estado_codigo==='PENDIENTE')@if(in_array($membresia->tipo_codigo ?? '',['PAREJA','FAMILIAR'],true) && (!$familia || !collect($beneficiarios)->contains(fn($b)=>$b->estado==='ACTIVO')))<div class="alert alert-info small">Primero configura el grupo y agrega al menos un beneficiario.</div><a href="#grupoMembresia" class="btn btn-outline-primary w-100">Agregar beneficiarios</a>@else<x-button :href="route('pagos.create',['membresia'=>$membresia->id])" class="w-100">Ir a registrar pago</x-button>@endif @else<div class="text-success"><i class="bi bi-check-circle me-2"></i>Membresía procesada</div>@endif</x-card></div></div>

@if($can('membresias.manage')&&!$membresia->es_terminal)
<div class="row g-4 mb-4"><div class="col-lg-6"><x-card title="Renovación rápida"><form method="POST" action="{{ route('membresias.renovar',$membresia->id) }}" class="row g-2">@csrf<div class="col-12"><select class="form-select" name="precio_membresia_id" id="precioRenovacion" required><option value="">Mismo plan u otro plan</option>@foreach($precios as $p)<option value="{{ $p->id }}" data-tipo="{{ $p->tipo_membresia_id }}">{{ $p->tipo }} · {{ number_format($p->precio,2) }} {{ $p->moneda }}</option>@endforeach</select><input type="hidden" name="tipo_membresia_id" id="tipoRenovacion"></div><div class="col-12"><label class="form-label">Nuevo inicio</label><input type="date" class="form-control" name="fecha_inicio" value="{{ \Illuminate\Support\Carbon::parse($membresia->fecha_fin)->addDay()->toDateString() }}" required></div><div class="col-12 form-check ms-1"><input class="form-check-input" type="checkbox" name="acepta_contrato" value="1" id="aceptaRenovacion" required><label class="form-check-label" for="aceptaRenovacion">Aceptar nuevo contrato y precio vigente</label></div><div><x-button type="submit">Crear renovación</x-button></div></form></x-card></div>
<div class="col-lg-6"><x-card title="Congelar acceso"><form method="POST" action="{{ route('membresias.congelar',$membresia->id) }}" class="row g-2">@csrf<input type="hidden" name="estado_membresia_id" value="{{ $membresia->estado_membresia_id }}"><div class="col-md-6"><label class="form-label">Desde</label><input type="date" class="form-control" name="fecha_inicio" required></div><div class="col-md-6"><label class="form-label">Hasta</label><input type="date" class="form-control" name="fecha_fin"></div><div class="col-md-3"><label class="form-label">Extensión</label><input type="number" class="form-control" name="dias_extension" min="0" max="365" value="0"></div><div class="col-md-9"><label class="form-label">Motivo</label><input class="form-control" name="motivo" required></div><div><x-button type="submit">Registrar congelación</x-button></div></form></x-card></div></div>
@endif

@if(in_array($membresia->tipo_codigo ?? '', ['PAREJA','FAMILIAR'], true) && $can('membresias.manage'))
<span id="grupoMembresia"></span>
<x-card :title="($membresia->tipo_codigo === 'PAREJA' ? 'Plan pareja' : 'Grupo familiar')" class="mb-4"><form method="POST" action="{{ route('membresias.familia',$membresia->id) }}" class="row g-2 mb-4">@csrf<input type="hidden" name="titular_cliente_id" value="{{ $membresia->cliente_id }}"><div class="col-md-9"><label class="form-label">Responsable del pago</label><select class="form-select" name="responsable_pago_cliente_id" required><option value="{{ $membresia->cliente_id }}">{{ $membresia->cliente }} (titular)</option>@foreach($clientesFamilia as $c)<option value="{{ $c->id }}">{{ $c->nombre }}</option>@endforeach</select></div><div class="col-md-3 d-flex align-items-end"><x-button type="submit" class="w-100">Configurar grupo</x-button></div><div class="col-12"><small class="text-muted">Este plan admite {{ $membresia->tipo_codigo === 'PAREJA' ? '1 beneficiario' : 'hasta 3 beneficiarios' }}. El límite se aplica automáticamente.</small></div></form>
@if($familia)<form method="POST" action="{{ route('membresias.beneficiarios.store',$membresia->id) }}" class="row g-2 border-top pt-3">@csrf<div class="col-md-7"><select class="form-select" name="cliente_id" required><option value="">Nuevo beneficiario</option>@foreach($clientesFamilia as $c)<option value="{{ $c->id }}">{{ $c->numero_socio }} · {{ $c->nombre }}</option>@endforeach</select></div><div class="col-md-3"><input class="form-control" name="parentesco" placeholder="Parentesco" required></div><div class="col-md-2"><x-button type="submit" class="w-100">Agregar +</x-button></div></form><table class="table mt-3"><thead><tr><th>Beneficiario</th><th>Parentesco</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($beneficiarios as $b)<tr><td>{{ $b->cliente }}</td><td>{{ $b->parentesco }}</td><td>{{ $b->estado }}</td><td>@if($b->estado==='ACTIVO')<form method="POST" action="{{ route('membresias.beneficiarios.destroy',[$membresia->id,$b->id]) }}" class="d-flex gap-1">@csrf @method('DELETE')<input class="form-control form-control-sm" name="motivo" placeholder="Motivo" required><button class="btn btn-sm btn-outline-danger">Retirar</button></form>@endif</td></tr>@empty<tr><td colspan="4">Sin beneficiarios.</td></tr>@endforelse</tbody></table>@endif</x-card>
@endif

<div class="row g-4"><div class="col-lg-7"><x-card title="Línea de tiempo">@forelse($lineaTiempo as $e)<div class="d-flex gap-3 border-bottom py-3"><i class="bi bi-circle-fill text-primary small mt-1"></i><div><strong>{{ $e->titulo }}</strong><div class="text-muted small">{{ $e->descripcion }}</div><small>{{ \Illuminate\Support\Carbon::parse($e->ocurrido_at)->format('d/m/Y H:i') }}</small></div></div>@empty<p class="text-muted">Sin eventos.</p>@endforelse</x-card></div><div class="col-lg-5"><x-card title="Congelaciones">@forelse($suspensiones as $s)<div class="border-bottom py-2">{{ $s->fecha_inicio }} – {{ $s->fecha_fin??'Abierta' }}<div class="small text-muted">{{ $s->motivo }}</div></div>@empty<p>Sin congelaciones.</p>@endforelse</x-card></div></div>

@if($can('membresias.changeStatus')&&!$membresia->es_terminal)<x-card title="Cancelación profesional" class="border-danger mt-4"><form method="POST" action="{{ route('membresias.cancelar',$membresia->id) }}" class="row g-2">@csrf<div class="col-md-3"><select class="form-select" name="categoria_id" required><option value="">Categoría</option>@foreach($categoriasCancelacion as $c)<option value="{{ $c->id }}">{{ $c->nombre }}</option>@endforeach</select></div><div class="col-md-2"><input type="date" class="form-control" name="fecha_efectiva" value="{{ now()->toDateString() }}" required></div><div class="col-md-3"><input class="form-control" name="motivo" placeholder="Motivo específico" required></div><div class="col-md-3"><input class="form-control" name="observaciones" placeholder="Observaciones opcionales"></div><div class="col-md-1"><x-button type="submit" variant="danger">Cancelar</x-button></div></form></x-card>@endif
@push('scripts')<script>document.getElementById('precioRenovacion')?.addEventListener('change',e=>document.getElementById('tipoRenovacion').value=e.target.selectedOptions[0]?.dataset.tipo||'');</script>@endpush
@endsection
