@extends('layouts.app')
@section('title', $usuario->name)
@section('content')
<x-page-header :title="$usuario->name" :subtitle="'@'.$usuario->username"/>
<div class="row g-4">
 <div class="col-lg-6"><x-card title="Cuenta"><dl class="row mb-0"><dt class="col-sm-4">Correo</dt><dd class="col-sm-8">{{ $usuario->email ?: 'No registrado' }}</dd><dt class="col-sm-4">Estado</dt><dd class="col-sm-8">{{ $usuario->activo ? 'Activo' : 'Inactivo' }}</dd><dt class="col-sm-4">Último acceso</dt><dd class="col-sm-8">{{ $usuario->ultimo_acceso_at ?: 'Nunca' }}</dd></dl></x-card></div>
 <div class="col-lg-6"><x-card title="Cambiar contraseña"><form method="POST" action="{{ route('usuarios.password',$usuario->id) }}" class="row g-2">@csrf @method('PUT')<div class="col-12"><input type="password" class="form-control" name="password" minlength="6" placeholder="Nueva contraseña" required></div><div class="col-12"><input type="password" class="form-control" name="password_confirmation" minlength="6" placeholder="Confirmar contraseña" required></div><div class="col-12"><input type="hidden" name="debe_cambiar_password" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="debe_cambiar_password" value="1" id="forzar"><label class="form-check-label" for="forzar">Solicitar cambio en el próximo acceso</label></div></div><div><x-button type="submit">Actualizar contraseña</x-button></div></form></x-card></div>
</div>
<x-card title="Roles asignados" class="mt-4"><div class="d-flex flex-wrap gap-2 mb-3">@forelse($rolesUsuario as $rol)<form method="POST" action="{{ route('usuarios.roles.destroy',$usuario->id) }}">@csrf @method('DELETE')<input type="hidden" name="usuario_id" value="{{ $usuario->id }}"><input type="hidden" name="rol_id" value="{{ $rol->id }}"><button class="btn btn-outline-primary btn-sm">{{ $rol->nombre }} <i class="bi bi-x"></i></button></form>@empty<span class="text-muted">Sin roles asignados.</span>@endforelse</div><form method="POST" action="{{ route('usuarios.roles.store',$usuario->id) }}" class="d-flex gap-2">@csrf<input type="hidden" name="usuario_id" value="{{ $usuario->id }}"><select class="form-select" name="rol_id" required><option value="">Agregar rol</option>@foreach($roles as $rol) @if($rol->activo)<option value="{{ $rol->id }}">{{ $rol->nombre }}</option>@endif @endforeach</select><x-button type="submit">Asignar</x-button></form></x-card>
@endsection
